/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package platformereditor;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import javax.swing.JPanel;

/**
 *
 * @author Julian Blazek
 */
public class SpriteViewer extends javax.swing.JFrame {

    private final BufferedImage sprite;

    /**
     * Creates new form SpriteViewer
     *
     * @param sprite
     */
    public SpriteViewer(BufferedImage sprite) {
        initComponents();
        this.sprite = sprite;
        pnDraw.setPreferredSize(new Dimension(sprite.getWidth(),sprite.getHeight()));
        this.pack();
        pnDraw.repaint();
    }

    void render(Graphics2D g) {
        g.drawImage(sprite, 0, 0, this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnDraw = new PaintPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(100, 100));
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        pnDraw.setPreferredSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout pnDrawLayout = new javax.swing.GroupLayout(pnDraw);
        pnDraw.setLayout(pnDrawLayout);
        pnDrawLayout.setHorizontalGroup(
            pnDrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 281, Short.MAX_VALUE)
        );
        pnDrawLayout.setVerticalGroup(
            pnDrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 339, Short.MAX_VALUE)
        );

        getContentPane().add(pnDraw);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnDraw;
    // End of variables declaration//GEN-END:variables
    
    class PaintPanel extends JPanel {

        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Graphics2D g2d = (Graphics2D) g;
            g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            render(g2d);
        }

    }
}
