/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package platformer.gui;

import platformer.Platformer;
import platformer.util.ComponentResizer;
import platformer.util.ComponentMover;

/**
 *
 * @author Florian Rost
 */
public class NewGUI extends javax.swing.JFrame {

    /**
     * Creates new form NewGUI
     */
    public NewGUI() {
        initComponents();

        ComponentMover cm = new ComponentMover(this, pnTitle);
        cm.setChangeCursor(false);

        ComponentResizer cr = new ComponentResizer();
        cr.registerComponent(this);
        cr.setSnapSize(new java.awt.Dimension(10, 10));
        cr.setMinimumSize(new java.awt.Dimension(800, 600));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnEinstellungen = new javax.swing.JButton();
        jbtnInformationen = new javax.swing.JButton();
        jbtnCredits = new javax.swing.JButton();
        jbtnSpielstarten = new javax.swing.JButton();
        btnBeende = new javax.swing.JButton();
        pnMain = new javax.swing.JPanel();
        lblInfo = new javax.swing.JLabel();
        lblVersion = new javax.swing.JLabel();
        btnBot = new javax.swing.JPanel();
        lblStart = new javax.swing.JLabel();
        lblSettings = new javax.swing.JLabel();
        pnTitle = new javax.swing.JPanel();
        lblClose = new javax.swing.JLabel();
        lblFramename = new javax.swing.JLabel();

        jbtnEinstellungen.setText("Einstellungen");
        jbtnEinstellungen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEinstellungenActionPerformed(evt);
            }
        });

        jbtnInformationen.setText("Informationen");

        jbtnCredits.setText("Credits");

        jbtnSpielstarten.setText("Spiel starten");
        jbtnSpielstarten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSpielstartenActionPerformed(evt);
            }
        });

        btnBeende.setText("Beenden");
        btnBeende.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBeendeActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setUndecorated(true);

        pnMain.setBackground(new java.awt.Color(192, 108, 132));

        lblInfo.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblInfo.setForeground(new java.awt.Color(255, 255, 255));
        lblInfo.setText("Platformer");

        lblVersion.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblVersion.setForeground(new java.awt.Color(204, 204, 204));
        lblVersion.setText(platformer.Platformer.VERSION);

        javax.swing.GroupLayout pnMainLayout = new javax.swing.GroupLayout(pnMain);
        pnMain.setLayout(pnMainLayout);
        pnMainLayout.setHorizontalGroup(
            pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVersion))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnMainLayout.setVerticalGroup(
            pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 398, Short.MAX_VALUE)
                .addComponent(lblVersion)
                .addContainerGap())
        );

        btnBot.setBackground(new java.awt.Color(53, 92, 125));

        lblStart.setBackground(new java.awt.Color(108, 91, 123));
        lblStart.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblStart.setForeground(new java.awt.Color(255, 255, 255));
        lblStart.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStart.setText("Spiel Starten");
        lblStart.setOpaque(true);
        lblStart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblStartMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblStartMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblStartMouseExited(evt);
            }
        });

        lblSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsc/images/Settings_64px.png"))); // NOI18N
        lblSettings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSettingsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSettingsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSettingsMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnBotLayout = new javax.swing.GroupLayout(btnBot);
        btnBot.setLayout(btnBotLayout);
        btnBotLayout.setHorizontalGroup(
            btnBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBotLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSettings)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 213, Short.MAX_VALUE)
                .addComponent(lblStart, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(306, Short.MAX_VALUE))
        );
        btnBotLayout.setVerticalGroup(
            btnBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBotLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStart, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSettings))
                .addContainerGap())
        );

        pnTitle.setBackground(new java.awt.Color(248, 177, 149));
        pnTitle.setPreferredSize(new java.awt.Dimension(0, 30));

        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsc/images/Close Window_32px.png"))); // NOI18N
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });

        lblFramename.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblFramename.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFramename.setText("Irgendein Name für das Fenster...");
        lblFramename.setFocusable(false);

        javax.swing.GroupLayout pnTitleLayout = new javax.swing.GroupLayout(pnTitle);
        pnTitle.setLayout(pnTitleLayout);
        pnTitleLayout.setHorizontalGroup(
            pnTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTitleLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lblFramename)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblClose))
        );
        pnTitleLayout.setVerticalGroup(
            pnTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTitleLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblFramename)
                .addContainerGap())
            .addGroup(pnTitleLayout.createSequentialGroup()
                .addComponent(lblClose)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 802, Short.MAX_VALUE)
            .addComponent(btnBot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(btnBot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnSpielstartenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSpielstartenActionPerformed

    }//GEN-LAST:event_jbtnSpielstartenActionPerformed

    private void jbtnEinstellungenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEinstellungenActionPerformed

    }//GEN-LAST:event_jbtnEinstellungenActionPerformed

    private void btnBeendeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBeendeActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnBeendeActionPerformed

    private void lblStartMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStartMouseEntered
        lblStart.setBackground(new java.awt.Color(246, 114, 128));
    }//GEN-LAST:event_lblStartMouseEntered

    private void lblStartMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStartMouseExited
        lblStart.setBackground(new java.awt.Color(108, 91, 123));
    }//GEN-LAST:event_lblStartMouseExited

    private void lblStartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStartMouseClicked
        this.setVisible(false);
        Platformer.startClicked();
    }//GEN-LAST:event_lblStartMouseClicked

    private void lblSettingsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSettingsMouseEntered
        lblSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsc/images/Settings_64px_hover.png")));
    }//GEN-LAST:event_lblSettingsMouseEntered

    private void lblSettingsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSettingsMouseExited
        lblSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsc/images/Settings_64px.png")));
    }//GEN-LAST:event_lblSettingsMouseExited

    private void lblSettingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSettingsMouseClicked
        new NewGUIEinstellungen().setVisible(true);
    }//GEN-LAST:event_lblSettingsMouseClicked

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblCloseMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(NewGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(NewGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(NewGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(NewGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new NewGUI().setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBeende;
    private javax.swing.JPanel btnBot;
    private javax.swing.JButton jbtnCredits;
    private javax.swing.JButton jbtnEinstellungen;
    private javax.swing.JButton jbtnInformationen;
    private javax.swing.JButton jbtnSpielstarten;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblFramename;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblSettings;
    private javax.swing.JLabel lblStart;
    private javax.swing.JLabel lblVersion;
    private javax.swing.JPanel pnMain;
    private javax.swing.JPanel pnTitle;
    // End of variables declaration//GEN-END:variables
}
